# Use uma imagem base que contém o SDK do .NET 8.0
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copie apenas os arquivos de projeto e restaure as dependências
COPY src/Mottu.Api/*.csproj ./src/Mottu.Api/
COPY nuget.config ./
RUN dotnet restore "./src/Mottu.Api/Mottu.Api.csproj"

# Copie todos os arquivos do projeto e compile a aplicação
COPY . ./
WORKDIR /app/src/Mottu.Api
RUN dotnet publish "./Mottu.Api.csproj" -c Release -o /app/out

# Use uma imagem runtime mais leve para a aplicação publicada
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Mottu.Api.dll"]
